language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# From: https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
matrix:
  include:
    - os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - python3 -m venv venv
        - source venv/bin/activate
        - python --version

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install sphinx sphinx_rtd_theme pytest
  - python setup.py build build_sphinx
  - python setup.py install

script:
  - pytest
